name: Matrix Workflow
on:
    push: 
        branches: 
            - main
jobs:
    build:
        continue-on-error: true
        strategy:
          matrix:
            node-version: [ 16, 18, 20 ]
            os: [ubuntu-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Setup Caching
              id: cache
              uses: actions/cache@v3
              with:
                path: ~./npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Code
              run: npm run build