name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: This is the name of the artifact
                required: true
                default: dist
                type: string
        # secrets:
        #   some-secret:
        #     required: true
        outputs:
          result:
            description: This is output
            value: ${{ jobs.deploy.outputs.outcome }}
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.step-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List Files
              run: ls
            - name: Deploying
              run: echo "Deploying Website...."
            - name: Set job output
              id: step-result
              run: echo "step-result=success" >> $GITHUB_OUTPUT